<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="UPSCRATCH" ignored="0" name="/RestAssuredAssignment" tests="2" failures="2" timestamp="23 Jan 2022 22:23:17 GMT" time="6.114" errors="0">
  <testcase name="testOTTResponse" time="4.906" classname="com.tests.IntigralOTTTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.report.ExtentLogger.logRequestAndResponse(ExtentLogger.java:24)
	at com.tests.IntigralOTTTests.testOTTResponse(IntigralOTTTests.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testOTTResponse -->
  <testcase name="validateErrorOnInvalidToken" time="0.803" classname="com.tests.IntigralOTTTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.report.ExtentLogger.logRequestAndResponse(ExtentLogger.java:24)
	at com.tests.IntigralOTTTests.validateErrorOnInvalidToken(IntigralOTTTests.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- validateErrorOnInvalidToken -->
</testsuite> <!-- /RestAssuredAssignment -->
